name: Update Spiele and Build HTML

on:
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update even if no changes detected'
        required: false
        default: false
        type: boolean

jobs:
  update-spiele:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Fetch all team games
      run: |
        echo "Starting spiele fetch for all teams..."
        node fetch-all.js
        echo "Spiele fetch completed"
        
    - name: Build HTML
      run: |
        echo "Starting HTML build..."
        node build-html.js
        echo "HTML build completed"
        
    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected"
          git status
        fi
        
    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true' || github.event.inputs.force_update == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update spiele and rebuild HTML - $(date '+%Y-%m-%d %H:%M:%S')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Summary
      run: |
        echo "## Update Summary" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Fetched latest games from basketball-bund.net for all teams" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Generated ICS files for all team schedules" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Rebuilt HTML with updated spiele data" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ steps.check_changes.outputs.changes }}" == "true" || "${{ github.event.inputs.force_update }}" == "true" ]]; then
          echo "- ✅ Committed and pushed changes to repository" >> $GITHUB_STEP_SUMMARY
        else
          echo "- ℹ️ No changes detected, repository unchanged" >> $GITHUB_STEP_SUMMARY
        fi