name: Update Basketball Calendars

# Run automatically every Monday at 6:00 AM Berlin time (4:00 AM UTC)
on:
  schedule:
    - cron: '0 4 * * 1'
  
  # Allow manual triggering from GitHub UI
  workflow_dispatch:

jobs:
  update-calendars:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Allow writing to repository contents
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run build script
      run: node build.js --quiet
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Changes detected:"
          git status --short
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/index.html docs/ics/*.ics
        git commit -m "🤖 Auto-update: Basketball calendars updated $(date +'%Y-%m-%d %H:%M UTC')"
        git push
    
    - name: No changes to commit
      if: steps.verify-changed-files.outputs.changed == 'false'
      run: echo "✅ No calendar updates needed - all data is current"